import type { Metadata } from "next";
import "./globals.css";

import { ApolloProvider } from "../lib/apolloProvider";

export const metadata: Metadata = {
  title: "Assignment Editor",
  // description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ApolloProvider>{children}</ApolloProvider>
      </body>
    </html>
  );
}
